#!/usr/bin/env python3
"""Evolution scoring constants; Chinese objective keywords are multilingual input tokens."""
from __future__ import annotations


TEMPLATE_PLACEHOLDER_MARKERS = [
    "# Problem Contract\n\n## Goal\n\n## Non-goals",
    "# Candidate Artifact\n\n## Summary\n\n## Design",
    "# Review Report\n\n## Hard gates\n\n## Claim ledger",
    "Proposed / Accepted / Rejected / Superseded",
    "- early_incremental / final_consistency_only / skipped",
    "- pass / pass_with_changes / fail",
]

CE_OBJECTIVES = [
    "solution_quality",
    "user_cognitive_gain",
    "evidence_strength",
    "feasibility",
    "risk_control",
    "simplicity",
    "adoption_likelihood",
    "novelty",
    "reversibility",
]

MIN_EVOLUTION_ROUNDS = 0
L1_EVOLUTION_ROUNDS = 1
MIN_L2_EVOLUTION_ROUNDS = 3
DEFAULT_EVOLUTION_ROUNDS = 5
DEFAULT_COMPLEX_EVOLUTION_ROUNDS = 10
MAX_EVOLUTION_ROUNDS = 20

OBJECTIVE_KEYWORDS = {
    "solution_quality": ["goal", "requirement", "coverage", "目标", "需求", "覆盖", "完整"],
    "user_cognitive_gain": ["choice", "feedback", "user cognitive", "认知", "选择", "反馈", "选项"],
    "evidence_strength": ["evidence", "source", "doctor", "eval", "验证", "证据", "评测"],
    "feasibility": ["small", "local", "command", "implementation", "可执行", "本地", "命令"],
    "risk_control": ["risk", "checkmodel", "guard", "policy", "风险", "评审", "策略"],
    "simplicity": ["configured dependency", "local runtime", "small patch", "standalone", "按需启用", "本地runtime", "小补丁"],
    "adoption_likelihood": ["workflow", "route", "standalone", "daily", "工作流", "路由", "日常"],
    "novelty": ["quality-diversity", "pairwise", "multihead", "evolution", "firework", "多路", "演化", "烟花"],
    "reversibility": ["reversible", "rollback", "task artifact", "no global", "可回滚", "不改全局"],
}

GENERATED_CANDIDATES: dict[str, str] = {}
"""Deprecated before the stable-runtime runtime.

Seed and mutated candidates are generated by the configured LLM.  This mapping
is intentionally empty so the source project cannot silently fall back to static
candidate templates.
"""


class EvolutionDefaults:
    """Named defaults for evolution and nexus-runtime decisions.

    The values are deterministic release defaults, not claims of universal
    optimality.  They preserve the existing behavior while making every tuning
    knob discoverable and overrideable from one module.
    """

    SEMANTIC_INFERRED_OBJECTIVE_CONFIDENCE: float = 0.82


class SearchSpaceDefaults:
    """Named thresholds for search-space coverage and objective gating."""

    LARGE_POOL_MIN_CANDIDATES: int = 4
    PROOF_MIN_CANDIDATES_FOR_CROSS_DOMAIN: int = 3
    SMALL_POOL_MIN_TOOL_CLASSES: int = 3
    SMALL_POOL_MIN_DIRECTIONS: int = 2
    META_RATIO_LARGE_POOL: float = 0.15
    META_RATIO_SMALL_POOL: float = 0.34
    FAMILY_ENTROPY_MIN_LARGE_POOL: float = 0.7
    HIGH_POTENTIAL_PROTECTION_ROUNDS: int = 5
    HIGH_POTENTIAL_PROTECTION_MAX_ROUNDS: int = 30
    BREAKTHROUGH_PROTECTION_THRESHOLD: float = 0.65
    NON_META_OBJECTIVE_CAP: float = 0.12
    NON_META_BREAKTHROUGH_CAP: float = 0.10

    MECHANISM_STEP_ACTION_MAX: float = 0.30
    MECHANISM_STEP_ACTION_WEIGHT: float = 0.05
    MECHANISM_VALIDATION_MAX: float = 0.20
    MECHANISM_VALIDATION_WEIGHT: float = 0.05
    MECHANISM_CLAIM_MAX: float = 0.15
    MECHANISM_CLAIM_WEIGHT: float = 0.03
    MECHANISM_KEYWORD_MAX: float = 0.55
    MECHANISM_KEYWORD_WEIGHT: float = 0.075
    MECHANISM_SCORE_FLOOR: float = 0.05
    MECHANISM_SCORE_BASE: float = 0.10

    META_OBJECTIVE_PROXIMITY_FLOOR: float = 0.08
    GENERAL_OBJECTIVE_BASE: float = 0.35
    PROOF_OBJECTIVE_BASE: float = 0.28
    PROOF_DIRECTION_BONUS: float = 0.14
    PROOF_SCALE_BONUS: float = 0.12
    PROOF_KEYWORD_BONUS: float = 0.15
    CROSS_DOMAIN_BONUS: float = 0.07
    GENERIC_OBJECT_LEVEL_BONUS: float = 0.20
    GENERIC_OBJECTIVE_KEYWORD_BONUS: float = 0.15
    GENERIC_CROSS_DOMAIN_BONUS: float = 0.08
    LOW_RELEVANCE_PENALTY: float = 0.15

    BREAKTHROUGH_BASE: float = 0.15
    BREAKTHROUGH_MECHANISM_WEIGHT: float = 0.25
    BREAKTHROUGH_CROSS_DOMAIN_BONUS: float = 0.20
    BREAKTHROUGH_DIRECTION_BONUS: float = 0.12
    BREAKTHROUGH_SCALE_BONUS: float = 0.12
    BREAKTHROUGH_KEYWORD_BONUS: float = 0.15
    BREAKTHROUGH_LOW_RELEVANCE_PENALTY: float = 0.10

    SCORE_01_TO_5_BASE: float = 1.0
    SCORE_01_TO_5_SCALE: float = 4.0
    META_INELIGIBLE_SCORE_CAP: float = 2.0
    META_TASK_PENALTY: float = 5.0
    PROOF_MECHANISM_SCORE_FLOOR: float = 2.5
    PROOF_LOW_MECHANISM_SCORE_CAP: float = 3.0
